AWSTemplateFormatVersion: 2010-09-09

Description: |
  This template launches an EC2 instance which enables SSH.

Resources:
  CFNInstance:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: ami-08e4e35cccc6189f4
      InstanceType: t2.micro
      KeyName: firstkey # Please use your own key name without .pem
      SecurityGroups: 
        - sg-0c6f506120f877c69
      Tags:
        - Key: Name
          Value: harun